apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: batbelt
  name: batbelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batbelt
  strategy: {}
  template:
    metadata:
      labels:
        app: batbelt
    spec:
      volumes:
        - name: public
          emptyDir: {}
      containers:
        - image: "docker.io/koma85/batbelt:latest"
          name: "batbelt"
          env:
            - name: ADMIN
              valueFrom:
                secretKeyRef:
                  name: batbelt
                  key: ADMIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: batbelt
                  key: PASSWORD
          ports:
          - containerPort: 8080
            name: terminal
          - containerPort: 8081
            name: web
          volumeMounts:
          - mountPath: /www/public
            name: public
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"

