{{- if .Values.clusteradmin -}}
{{- $fullName := include "batbelt.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "batbelt.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: "{{ $fullName }}-cluster-admin"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
{{- end }}