{{- if .Values.openshift.privileged -}}
{{- $fullName := include "batbelt.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $fullName }}"
  labels:
    {{- include "batbelt.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: {{ include "batbelt.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}