{{- if .Values.ingress.enabled -}}
{{- $fullName := include "batbelt.fullname" . -}}
{{- $labels := include "batbelt.labels" . | nindent 4 }}
{{- $annotations := .Values.ingress.annotations }}
{{- $GitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- range .Values.ingress.hosts }}
{{- if semverCompare ">=1.18-0" $GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ .name }}"
  labels:
    {{- $labels }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} #with
spec:
  rules:
    - http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .backend.service.name }}
      {{- if .host }}
      host: {{ .host | quote }}  
      {{- end }} # ifhost
---
{{- end }} #range
{{- end }} # end
