apiVersion: v1
stringData:
  ADMIN: {{ .Values.service.terminal.user | default "admin" | quote }}
  PASSWORD: {{ .Values.service.terminal.password | default "changeme" | quote }}
kind: Secret
metadata:
  name: {{ include "batbelt.fullname" . }}
