apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: batbelt
  name: batbelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batbelt
  strategy: {}
  template:
    metadata:
      labels:
        app: batbelt
    spec:
      containers:
      - image: "quay.io/koma/batbelt:latest"
        name: "batbelt"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
            
            
