apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: batbelt
  name: terminal
spec:
  port:
    targetPort: terminal
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: ""
    name: batbelt
status: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: batbelt
  name: web
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: ""
    name: batbelt
    weight: null
