# Default values for batbelt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/koma85/batbelt
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clusteradmin: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

effimeralvolume: true

service:
  service_type: ClusterIP
  terminal:
    port: 8080
    user: admin
    password: changeme
  webserver:
    port: 8081

routes: "Use ingresses we are in 2021"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: "batbweb.wayneenterprises.com" # batbelt.wayneenterprises.com
      name: webserver
      path: /
      pathType: Prefix
      backend:
        service:
          name: webserver
    - host: "batbelt.wayneenterprises.com" # batbelt.wayneenterprises.com
      name: terminal
      path: /
      pathType: Prefix
      backend:
        service:
          name: terminal

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
