name: Release New Helm Chart

# Using a reduced set of platforms. v6 and v7 is rarely used.
# platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Define Container TAG
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Chart | No Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: batbelt
          repository: appany
          tag: ${{ steps.date.outputs.DATE }}
          path: charts/batbelt # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          update_dependencies: 'true' # Defaults to false
