name: Full Cycle Release

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-new-image:
    runs-on: ubuntu-latest
    steps:
      - name: Define Container TAG
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ steps.date.outputs.DATE }}
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - uses: nguyenvukhang/semver-increment@v1
        id: semver
        continue-on-error: false
        with:
          increment: 'patch'
          # identifier: 'alpha'
          version-file: 'charts/Chart.yaml'
          version-regex: '^appVersion = "(.*)"'

      - name: Get error message (if any)
        run: echo ${{ steps.semver.outputs.error }}

      - name: Get the new latest version after incrementing
        run: echo ${{ steps.semver.outputs.version }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: Run chart-releaser batbelt
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_existing: true
