name: Test

on:
  workflow_dispatch: {}

jobs:
  semvercheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Fetch history
        run: git fetch --prune --unshallow


      - uses: nguyenvukhang/semver-increment@v1
        id: semver
        continue-on-error: false
        with:
          increment: 'patch'
          # identifier: 'alpha'
          version-file: 'charts/Chart.yaml'
          version-regex: '^appVersion = "(.*)"'
    
      - name: Get error message (if any)
        run: echo ${{ steps.semver.outputs.error }}
    
      - name: Get the new latest version after incrementing
        run: echo ${{ steps.semver.outputs.version }}

