apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batbelt.fullname" . }}
  labels:
    {{- include "batbelt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "batbelt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "batbelt.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.effimeralvolume }}
      volumes:
        - name: public
          emptyDir: {}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "batbelt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "batbelt.fullname" . }}
                  key: ADMIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "batbelt.fullname" . }}
                  key: PASSWORD
          ports:
            - containerPort: 8080
              name: terminal
            - containerPort: 8081
              name: web
          {{- if .Values.effimeralvolume }}
          volumeMounts:
            - mountPath: /www/public
              name: public
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: web
          readinessProbe:
            httpGet:
              path: /
              port: web
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
