apiVersion: v1
kind: Service
metadata:
  name: {{ include "batbelt.fullname" . }}
  labels:
    {{- include "batbelt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.service_type }}
  ports:
    - port: {{ .Values.service.terminal.port }}
      protocol: TCP
      targetPort: terminal
      name: terminal
    - port: {{ .Values.service.webserver.port }}
      protocol: TCP
      targetPort: web
      name: webserver
  selector:
    {{- include "batbelt.selectorLabels" . | nindent 4 }}
